# vim: expandtab tabstop=2 shiftwidth=2
name: IPA Down

env:
  PYTHONIOENCODING: utf-8
  WEB_SERVER_ADDRESS: http://175.10.91.86:7733

# Allow Release
permissions: write-all

on: [push]
  # workflow_dispatch:

jobs:
  download_ipa:
    name: 'IPATool Operations'
    runs-on: "windows-latest"
    steps:
      - name: step 1 --- request task id
        run: |
          WEB_TASK_ID=`curl $WEB_SERVER_ADDRESS/scriptTaskIdRequest`
          # WEB_TASK_ID="2024_06_20_0001"
          echo "TASK_ID=$WEB_TASK_ID"
          if [[ "$WEB_TASK_ID" == "" ]]; then
            echo "No task available"
            exit 1
          fi

          # 保存环境变量
          echo "TASK_ID=$WEB_TASK_ID" >> $GITHUB_ENV
        shell: bash

      - name: step 2 --- Set up git repository
        uses: actions/checkout@v2

        # Command
      - name: step 3 --- Setup ipatool-py
        run: |
          pip3 install -r ipatool-py/requirements.txt
          mkdir -p ipaDown

          
          echo "TASK_ID=${{ env.TASK_ID }}"
        shell: bash

      # - name: "Upload package"
      #   uses: NyaMisty/upload-artifact-as-is@master
      #   with:
      #     path: test\*

        # 安装iTunes和登录iTunes
      - name: step 4 --- Setup iTunes Header Service
        uses: ./iTunesInstallAndLoginAction


      - name: step 5 --- Start Python Task
        run: |
          python3 ipatool-py/main.py ${{ env.WEB_SERVER_ADDRESS }} ${{ env.TASK_ID }}
        shell: bash

      - name: step 6 --- Upload ipa to qiniu
        run: |
          UPLOAD_PATH="./output/${{ env.TASK_ID }}/${{ env.TASK_ID }}"
          echo "UPLOAD_PATH=$UPLOAD_PATH"

          # 上传ipa到七牛云
          ./qshell/qshell.exe account IAM-EoI9EYPycpcN8ptQWbRhcnmkgHk_AomfwqtJgqCQ DRvt4NlC4paHK7YdYc69GnkybCbWUrkUqu34Bl5g2o4S AppStoreHistoryIpa
          ./qshell/qshell.exe qupload2 --src-dir=$UPLOAD_PATH --bucket=test-histroy-ipa
        shell: bash
        
